### ISSUE TITLE
之前datepicker伸展的问题

### ISSUE THREAD

**Issue by lemondreamtobe** [xxapp/ane#14]
之前有需求就是说要往上伸展。
当我固定外围div高度，设置overflow:hidden;
此时页面高度刚好适合没有滚动条
第一次加载的时候，点击datepicker，还是往下伸展，因为overflow:hidden;所以时间选择那里被隐藏了无法选择时间。
点击其他地方把datepicker收缩回来再次点击又可以往上伸展，就是说第一次点击之后都可以往上伸展，不知道是不是bug，看看能不能优化，做一个:widget做一个属性选项控制他网上或者往下伸展。

**Comment by xxapp** [comment]
我放一个属性出来吧

**Comment by lemondreamtobe** [comment]
非常感谢

**Comment by xxapp** [comment]
@lemondreamtobe 升级 ane@0.1.7

https://xxapp.github.io/ane/#!/changelog
