### ISSUE TITLE
ms-tree-select数据问题

### ISSUE THREAD

**Issue by lemondreamtobe** [xxapp/ane#15]
ms-tree-select组件可获取的数据太少了

    title 
    key 
    children
一般每一条tree会用这三个数据来做ms-tree-select，但是实际的项目在选择树下拉的时候需要取得这条tree里面的更多信息。比如id啊之类的数据，而组件里面onChange方法里只能获得key值。
    title 
    key 
    children
    id
    qq
    weixin
我想要的就是能获取上面这些，因为文档不够详尽，不知道可否有方法。

**Comment by xxapp** [comment]
@lemondreamtobe 升级 ane@0.1.7

https://xxapp.github.io/ane/#!/changelog
