### ISSUE TITLE
tree设置全局setting问题

### ISSUE THREAD

**Issue by xieminhui** [xxapp/ane#26]
比如我初始化时需要设置ztree的自定义setting，类似这样子，
var setting = {
		data : {
			key : {
				children : "children",
				name	 : "displayName"
			}
		},
		check: {
			enable: true,
			chkboxType: { "Y": "p", "N": "p" }
		},
		view: {
			fontCss: getFontCss,
			addHoverDom: addHoverDom,
			//removeHoverDom: removeHoverDom,
			nameIsHTML: true
		},
		callback : { 
			beforeClick: beforeClick,
			beforeExpand:beforeExpand,
			onExpand: zTreeOnExpand,
			onCollapse: zTreeOnCollapse,
			onCheck: onChecked
		}
	};
我没有看到组件里面有相应的参数可以传递，请问这个要怎么做呢？

**Comment by lz2007** [comment]
直接用 jq jqtree 插件
