### ISSUE TITLE
table组件

### ISSUE THREAD

**Issue by fisher-zwl** [xxapp/ane#9]
表格序号是否可以自动排序

**Comment by xxapp** [comment]
能详细说下自动排序指的是什么吗？

**Comment by fisher-zwl** [comment]
后台请求到的数据，没有返回相应的序号，表格初始后序号自动补上1、2、3、4
序号       数据
1             aaa
2             bbb

**Comment by xxapp** [comment]
更新 ane@0.1.3

在 `<ms-table>` 下面这样用 `<ms-table-header :widget="{title:'序号',type:'index'}"></ms-table-header>`

**Comment by fisher-zwl** [comment]
更新后使用，只能当前页排序，翻页的时候，数据又会重新开始排序，能不能自动排序所有的数据

**Comment by xxapp** [comment]
table 组件只负责展示，这种需求不太可能在组件库里实现。

你可以这样做，手动给你的数据加上 id 字段，然后再用一下代码展示出来：

```html 
<ms-table-header :widget="{title:'序号',dataIndex:'id'}"></ms-table-header>
```
